# Generated by Django 5.0.7 on 2024-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='paper_covers/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
