# Generated by Django 5.0.7 on 2024-07-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_author_alter_paper_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='paper',
            name='document',
            field=models.FileField(upload_to='papers/'),
        ),
    ]
